name: "Сообщить о проблеме"
description: "Если что-то работает не так, как ожидалось."
type: Bug
body:
  - type: markdown
    attributes:
      value: "## В игре есть кнопка «Bug Report» в правом верхнем углу игры, при её нажатии часть информации ниже заполнится автоматически."

  - type: checkboxes
    id: feature_scope
    validations:
      required: true
    attributes:
      label: "Категория бага"
      description: "К какому типу контента относится проблема?"
      options:
        - label: "Код 👨‍💻"
        - label: "Спрайты 🎨"
        - label: "Карты 🗺️"
        - label: "Перевод/Описание 🧠"


  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Описание"
      description: "Опишите одну проблему как можно подробнее"

  - type: textarea
    id: whatmusthappen
    validations:
      required: true
    attributes:
      label: "Что должно было произойти"

  - type: textarea
    id: whathappenow
    validations:
      required: true
    attributes:
      label: "Что произошло на самом деле"

  - type: textarea
    id: reproduction
    attributes:
      label: "Шаги воспроизведения"
      description: "Если приемлемо, опишите шаги для воспроизведения проблемы"
      placeholder: |
        1. Найти автолат
        2. Открыть его меню, кликнул ЛКМ
        3. Получить лаги

  - type: textarea
    id: additional
    attributes:
      label: "Дополнительная информация:"
      description: |
        Вы можете добавьте скриншоты, чтобы помочь описать вашу проблему
        **Подсказка**: Вы можете прикрепить изображения, щелкнув по области ниже для её выделения,
         а затем перетащите в неё файлы
