name: "Оставить предложение"
description: "Любые идеи."
type: Feature
body:
  - type: checkboxes
    id: feature_scope
    attributes:
      label: "Что потребует изменений?"
      description: "Выберите тип изменений"
      options:
        - label: "Код 👨‍💻"
        - label: "Спрайты 🎨"
        - label: "Карты 🗺️"
        - label: "Перевод/Описание 🧠"

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Описание"
      description: "Опишите идею"
